### PR TITLE
"it" branch

### PR DESCRIPTION
**Pull request by richardmacduff**
Hello, I read up on the fork&branch workflow and asked knowleadgable colleagues.
In the end, I:
- cloned my fork of your repo (remote =origin)
- added to the clone an extra remote for your repo and called it "upstream"
- added an "it" branch to my clone
- copied the italian material in such branch
- committed the changes and pushed to origin/it (=my fork)
- at this point, I cannot of course push to upstream (nor would I try without your ok first) because permissions.

So, opening this PR instead as you suggested.
My next step would be to work on an additional sheet to PR in the master branch (plus its obvious translation)

Thank you, compliments on the good work and have a great weekend!
W

### CODE REVIEW

**Comment by LaboCNIL** [comment]
Dear Richardmacduff,

Many thanks for your contribution! Yet, the section "Misure minime da attivare" 
hasn't been translated on this page :
https://github.com/richardmacduff/GDPR-Developer-Guide/blob/it/13-Preparati%20all'esercizio%20dei%20diritti%20degli%20interessati.md

Is this an oversight? We won't be able to merge this work if the translation isn't fully complete.

Best regards

**Comment by richardmacduff** [comment]
> Dear Richardmacduff,
> 
> Many thanks for your contribution! Yet, the section "Misure minime da attivare"
> hasn't been translated on this page :
> https://github.com/richardmacduff/GDPR-Developer-Guide/blob/it/13-Preparati%20all'esercizio%20dei%20diritti%20degli%20interessati.md
> 
> Is this an oversight? We won't be able to merge this work if the translation isn't fully complete.
> 
> Best regards

Oh merde.
Sorry, I was so focused on ont screwing up as a noob at collaborative git that I noobed out on simpler stuff. 
Of course, it was overlooked and it's now fixed. I'll also recheck all sheets to make sure there are no other stupid things laying around,
Won't happen again, sorry for the disturbance.
W

**Comment by richardmacduff** [comment]
OK, now I have also corrected all typos. Things should work or it's *another* round of beers on  me
Thank you,
W

**Comment by richardmacduff** [comment]
hello, I see the merge has still not been sorted out. What are these conflicts that are mentioned? I git pull'ed the master branch and only worked on the it branch. Sorry for the noobness, please advise.
Thank you,
W

**Comment by LaboCNIL** [comment]
Huge thanks for your hard work!

Your pull request has been reviewed by Garante per la Protezione dei Dati Personali and integrated to the "it" branch of this git :
https://github.com/LINCnil/GDPR-Developer-Guide/tree/it

A pdf version of the guide is available here : 
https://github.com/LINCnil/GDPR-Developer-Guide/releases

In case you want to submit new contributions, can you please do so in this new branch?

Bests,

**Pull request closed without merging**
